import {parseContent, type Project, ProjectSchema} from "./schema.ts";

export type {Project};

const rawHobbyProjects = [
    {
        name: "EuroBonus Buddy",
        tagline: "I track my SAS EuroBonus status-point collecting in a personal Excel file with a dozen tabs — handy for me, but I don't want to hand over the whole document when friends and I compare notes on the cheapest way to the next tier, and it's honestly a mess to look at. EuroBonus Buddy is meant to replace it: a personal tracker for point and status data, plus a planner that compares different paths to a status goal — buying points outright, stacking car rentals, or a mix of both — ranked by cost or by speed, with a clean overview worth actually sharing. The plan is for anyone to be able to create their own account and track their own progress the same way, not just me.",
        status: "Planned",
        tags: ["React", "TypeScript", "Vite"],
        githubUrl: "https://github.com/Cecinordahl/eurobonusbuddy",
        // liveUrl: "https://<your-live-site>",
        details: {
            summary: "Enter your current status points, target tier, and months remaining in your qualification period; the planner generates a handful of candidate plans to close the gap and ranks them by either total cost or how fast they'd complete.",
            highlights: [
                "The \"buy Level Points\" option encodes SAS's actual eligibility rules rather than just offering a slider: it checks you're at least 6 months into the qualification period and have already earned the tier-specific minimum before allowing a purchase, then caps the amount at the tier's official ceiling and rounds to SAS's 100-point purchase blocks.",
                "Plans with an unknown cost (like car rentals, whose real price isn't modeled yet) are still shown and ranked, but explicitly flagged with a warning rather than silently guessed at or hidden, so an uncosted plan is never mistaken for a free one.",
                "The planner generates several candidate plans for the same goal — buying points outright, stacking multiple car rentals, or a hybrid of both — and ranks them by whichever optimization mode is selected: cheapest total cost, or fastest to close the gap.",
            ],
        },
    },
    {
        name: "WorkoutChallenge",
        tagline: "Inspired by Oslo Maraton's Julechallenge — pick a total distance and hit it by Christmas Eve — but frustrated it only ran in December with a flat, unskippable daily distance, I wanted that same not-knowing-what-today-brings motivation available year-round. WorkoutChallenge lets you set any date range and a total km goal, then generates a varied day-by-day plan with harder 'hero' days and lighter recovery days instead of splitting the distance evenly, tracking completion, streaks, and points with automatic Strava sync.",
        status: "Live",
        tags: ["React", "TypeScript", "Firebase", "Tailwind CSS", "Strava API", "Vercel"],
        githubUrl: "https://github.com/Cecinordahl/workout-challenge",
        liveUrl: "https://workout-challenge-app.vercel.app/",
        images: [
            "/images/projects/workout-challenge/1.png",
            "/images/projects/workout-challenge/2.png",
            "/images/projects/workout-challenge/3.png",
            "/images/projects/workout-challenge/4.png",
            "/images/projects/workout-challenge/5.png",
            "/images/projects/workout-challenge/6.png",
        ],
        details: {
            summary: "You set a total distance or time goal, a daily minimum and maximum, and a date range; the app generates a randomized day-by-day plan within those bounds and tracks your progress against it, syncing automatically from Strava.",
            highlights: [
                "The daily plan is generated by a seeded-random engine that distributes the total goal unevenly across the challenge window — ramping difficulty gradually week over week, easing the final week, and mixing in randomized \"hero\" days (1.4-1.6x the baseline) and lighter recovery days (0.5-0.6x) — instead of splitting the goal into equal daily chunks.",
                "Strava activities sync automatically: a webhook subscription notifies a Vercel serverless function the moment a qualifying run posts, which matches it to that day's active challenge and logs it without the user opening the app.",
                "Hero days are worth double the points of normal or recovery days, and the streak counter tolerates days a user explicitly marks as skipped while still breaking on days left unmarked, rewarding honest tracking over silently missed days.",
                "Points and streak calculations are deliberately duplicated between the client and the Vercel functions (each copy comments pointing at its counterpart) so the UI and the webhook-driven auto-logging path stay consistent without sharing a runtime.",
            ],
            challenges: [
                "Firebase Admin's auth module pulled in a JWT library that's ESM-only, which crashed every serverless function in production with ERR_REQUIRE_ESM the moment the new Strava routes started calling it — fixed by pinning that dependency to its last dual CJS/ESM major version via an npm override.",
                "The daily min/max distance inputs used native number-input steppers, which increment from whatever value is already there without rounding — so starting from a suggested 1.2km and clicking up repeatedly produced 2.2, 3.2, and so on instead of whole numbers; replaced with a custom stepper that rounds to the nearest step and clamps both bounds to the challenge's total goal.",
                "A day with no logged result used to be permanently marked missed with no way back, silently breaking the streak — now the next day surfaces a banner letting the user confirm they skipped it, log it manually, or re-check Strava for that specific date.",
            ],
        },
    },
    {
        name: "Americano",
        tagline: "Some friends and I started playing Americano at padel, and the app we used worked fine with 4+ players and plenty of time — but with only 3 players, or with just 10 minutes left on a court booking after a longer game, none of the apps I tried had a mode that fit. Americano is my own version built to cover those gaps: it supports 3-player games and lets you pick the shortest possible format for whatever group size and time you actually have.",
        status: "Planned",
        tags: ["Swift", "SwiftUI", "SwiftData"],
        // githubUrl: "https://github.com/<you>/<repo>",
        // liveUrl: "https://<your-live-site>",
        details: {
            summary: "This iOS app generates and manages Americano-style tournaments for racket sports, with support for both traditional doubles Americano (4+ players) and a custom 3-player singles variant. Users create a tournament, get an auto-generated match schedule, record scores round by round, and track a live leaderboard, with everything saved locally so a tournament can be resumed later.",
            highlights: [
                "Built as a native iOS app in SwiftUI with SwiftData persistence, so tournaments, players, matches, and scores are saved automatically between launches.",
                "The 3-player mode uses a custom singles rotation — each round has one player sit out while the other two play, and the resting slot rotates evenly so everyone alternates fairly between playing and resting.",
                "Doubles scheduling rotates player order between rounds and groups players into courts of four (court count is configurable so multiple matches can run per round), auto-forming teams and assigning byes when the player count doesn't divide evenly.",
                "Doubles score targets are restricted to multiples of four (8, 12, 16, 20...) so every player serves the same number of times, matching how Americano is conventionally played — a rule most Americano apps don't enforce.",
                "Score entry isn't blocked, but a mismatched total against the configured points target shows a warning, and a match must be explicitly locked before it counts toward the leaderboard, so an in-progress or miskeyed score can't silently skew the standings.",
            ],
            challenges: [
                "Standard Americano scheduling assumes four players, so 3-player games needed a custom rotation: one player sits out each round while the other two play, with the resting slot rotating evenly across players.",
                "A score target like 11 points gave players an unequal number of serves in doubles — fixed by restricting doubles targets to multiples of four so serves always come out even.",
                "Switching between saved tournaments was leaking standings from one tournament into another because the leaderboard wasn't scoped to the active tournament's matches — fixed by recalculating each player's total directly from the current tournament's stored matches.",
                "Adding new persisted properties to the SwiftData models broke the local model container at launch — resolved by rebuilding the local development data store so its schema matched the updated models.",
            ],
        },
    },
    {
        name: "Daily AI Digest",
        tagline: "Email summaries of credible AI news from the last 24 hours.",
        status: "Planned",
        tags: ["Automation", "Email", "AI"],
        // githubUrl: "https://github.com/<you>/<repo>",
        // liveUrl: "https://<your-live-site>",
    },
    {
        name: "Trivia Arena",
        tagline:
            "I was usually the one building the Kahoot quiz for game night, and Kahoot has no way to generate a quiz automatically by category — I had to write every question and answer myself, which meant I already knew them all and couldn't actually play. Trivia Arena is my own answer to that: a real-time, Jeopardy-style board across 12 categories where teams buzz in, wrong or missed answers open a steal for the other team, and everything syncs live over WebSocket. Today's board runs on a curated 60-question bank; automatic per-category question generation — the actual fix for not being able to play my own game — is next.",
        status: "In progress",
        tags: ["React", "TypeScript", "Spring Boot", "Java"],
        githubUrl: "https://github.com/Cecinordahl/trivia-arena",
        liveUrl: "https://trivia-arena.onrender.com/",
        details: {
            summary: "A host creates a room, organizes players into teams, and starts the game from a lobby; the board shows 12 categories × 5 point values, and whoever's turn it is picks a question for everyone to answer against a host-configurable countdown.",
            highlights: [
                "Each question round is a server-authoritative two-phase timer: the picking team's exclusive window to answer, followed — on a wrong or missed answer — by a steal window opened to every other team, each phase running its own scheduled timeout and broadcasting the change over WebSocket.",
                "Game state (rooms, teams, board, scores) is pushed to every connected client in real time over WebSocket/STOMP, so the shared board, buzz-ins, and score changes stay in sync across host and player screens without polling.",
                "The frontend and backend ship as a single Docker image — Spring Boot serves the built React app as static resources from its own JAR — so the whole game runs from one process on Render's free tier.",
                "The host sets an answer countdown between 10 and 300 seconds when starting the game, broadcast live to every client so everyone sees the same clock.",
            ],
            challenges: [
                "Expanding from a handful of categories to twelve for full coverage broke the fixed-width board — columns started overlapping their own text — fixed by making the board grid scroll horizontally with a sane per-column minimum width instead of squeezing everything to fit.",
            ],
        },
    },
    {
        name: "Casa 360",
        tagline: "Landing page for house rental",
        status: "Planned",
        tags: ["InsertTag1Here", "InsertTag2Here", "InsertTag2Here"],
        // githubUrl: "https://github.com/<you>/<repo>",
        // liveUrl: "https://<your-live-site>",
    },
    {
        name: "TanPlan",
        tagline: "A mobile-first sunscreen planner that schedules reapplication reminders throughout the day based on live UV forecasts, swims, and skin sensitivity.",
        status: "Beta",
        tags: ["React", "TypeScript", "Firebase", "Tailwind CSS"],
        githubUrl: "https://github.com/Cecinordahl/tan-plan",
        liveUrl: "https://tan-plan.vercel.app/",
    },
    {
        name: "Braut & Rosé",
        tagline: "Four couples on the same summer trip, arriving on different dates from different cities and staying in a mix of shared and separate places — all the coordinating was happening in a group chat, where details got buried and re-asked constantly. I built a shared trip planner so everyone could see the same itinerary notes, bookings, and schedules in real time and add to them directly, instead of scrolling back through chat history.",
        status: "Live",
        tags: ["React", "Vite", "Firebase", "Tailwind CSS"],
        githubUrl: "https://github.com/Cecinordahl/braut-og-rose",
        liveUrl: "https://braut-og-rose.vercel.app/",
        images: [
            "/images/projects/braut-og-rose/1.png",
            "/images/projects/braut-og-rose/2.png",
            "/images/projects/braut-og-rose/3.png",
            "/images/projects/braut-og-rose/4.png",
        ],
        details: {
            summary: "No accounts — everyone in the group unlocks the same shared trip with one passcode, and every device sees itinerary notes, bookings, and match/flight state update live via Firestore.",
            highlights: [
                "Live flight status via the AeroDataBox API, proxied through a Vercel serverless function so the RapidAPI key never reaches the client; results are cached in localStorage for 15 minutes to stay within the free tier's quota, with a manual refresh and a graceful fallback if the provider is unavailable.",
                "Live World Cup schedule and scores via ESPN's public scoreboard endpoint (no API key needed, since API-Football's free tier excludes the 2026 tournament) — matches are looked up by expected UTC kickoff time rather than team name, since most fixtures start as 'winner of X' placeholders that resolve automatically as ESPN's data updates through the earlier rounds.",
                "Real-time shared editing via Firebase Firestore's onSnapshot listeners — day notes, bookings, and match state sync live across every device in the group with no login, just a shared passcode on first visit.",
                "Packing lists export as plain text via the Web Share API (falling back to clipboard copy), formatted to paste cleanly into Notes and become a checklist there.",
                "Third-party fetches for flights and matches are staggered client-side to stay under provider rate limits, with a server-side retry-once-on-429 for extra resilience.",
            ],
            challenges: [
                "Penalty-shootout wins showed as a flat 0-0: ESPN marks these games with a separate STATUS_FINAL_PEN status and reports each team's shootoutScore apart from the 90-minute score, which the UI was initially dropping — fixed by reading and displaying the shootout score explicitly.",
                "All three tracked flights fetched simultaneously when the info card opened, tripping AeroDataBox's per-second rate limit — fixed by staggering client-side fetches 1.5s apart per flight and adding a server-side retry-once-on-429 with a clearer 'too many requests' message instead of a generic error.",
                "A data-loss race condition: booking add/update/delete could fire before the initial Firestore snapshot had loaded, rebuilding the bookings array from empty defaults and silently wiping everyone else's bookings — fixed by making those actions no-op until real data has loaded, with a loading state shown instead of exposing the controls early.",
            ],
        },
    },
    {
        name: "Pocket Phrases",
        tagline: "A situation-based travel phrase learner that builds short Spanish/French/German lessons for a chosen or described situation, with a Norwegian Bokmål UI.",
        status: "Live",
        tags: ["React", "TypeScript", "Java", "Spring Boot", "Anthropic API", "Firebase"],
        githubUrl: "https://github.com/Cecinordahl/pocket-phrases",
        liveUrl: "https://pocket-phrases.vercel.app",
    },
];

export const hobbyProjects: Project[] = parseContent(ProjectSchema, rawHobbyProjects, "content/projects.ts");
