import {parseContent, type Project, ProjectSchema} from "./schema.ts";

export type {Project};

const rawHobbyProjects = [
    {
        name: "EuroBonus Buddy",
        tagline: "Help EuroBonus hunters maximize points and status progress with SAS.",
        status: "Planned",
        tags: ["React", "TypeScript", "Spring"],
        githubUrl: "https://github.com/Cecinordahl/eurobonusbuddy",
        // liveUrl: "https://<your-live-site>",
    },
    {
        name: "WorkoutChallenge",
        tagline: "Inspired by Oslo Maraton's Julechallenge — pick a total distance and hit it by Christmas Eve — but frustrated it only ran in December with a flat, unskippable daily distance, I wanted that same not-knowing-what-today-brings motivation available year-round. WorkoutChallenge lets you set any date range and a total km goal, then generates a varied day-by-day plan with harder 'hero' days and lighter recovery days instead of splitting the distance evenly, tracking completion, streaks, and points with automatic Strava sync.",
        status: "Live",
        tags: ["React", "TypeScript", "Firebase", "Tailwind CSS", "Strava API", "Vercel"],
        githubUrl: "https://github.com/Cecinordahl/workout-challenge",
        liveUrl: "https://workout-challenge-app.vercel.app/",
        images: [
            "/images/projects/workout-challenge/1.png",
            "/images/projects/workout-challenge/2.png",
            "/images/projects/workout-challenge/3.png",
            "/images/projects/workout-challenge/4.png",
            "/images/projects/workout-challenge/5.png",
            "/images/projects/workout-challenge/6.png",
        ],
        details: {
            summary: "You set a total distance or time goal, a daily minimum and maximum, and a date range; the app generates a randomized day-by-day plan within those bounds and tracks your progress against it, syncing automatically from Strava.",
            highlights: [
                "The daily plan is generated by a seeded-random engine that distributes the total goal unevenly across the challenge window — ramping difficulty gradually week over week, easing the final week, and mixing in randomized \"hero\" days (1.4-1.6x the baseline) and lighter recovery days (0.5-0.6x) — instead of splitting the goal into equal daily chunks.",
                "Strava activities sync automatically: a webhook subscription notifies a Vercel serverless function the moment a qualifying run posts, which matches it to that day's active challenge and logs it without the user opening the app.",
                "Hero days are worth double the points of normal or recovery days, and the streak counter tolerates days a user explicitly marks as skipped while still breaking on days left unmarked, rewarding honest tracking over silently missed days.",
                "Points and streak calculations are deliberately duplicated between the client and the Vercel functions (each copy comments pointing at its counterpart) so the UI and the webhook-driven auto-logging path stay consistent without sharing a runtime.",
            ],
            challenges: [
                "Firebase Admin's auth module pulled in a JWT library that's ESM-only, which crashed every serverless function in production with ERR_REQUIRE_ESM the moment the new Strava routes started calling it — fixed by pinning that dependency to its last dual CJS/ESM major version via an npm override.",
                "The daily min/max distance inputs used native number-input steppers, which increment from whatever value is already there without rounding — so starting from a suggested 1.2km and clicking up repeatedly produced 2.2, 3.2, and so on instead of whole numbers; replaced with a custom stepper that rounds to the nearest step and clamps both bounds to the challenge's total goal.",
                "A day with no logged result used to be permanently marked missed with no way back, silently breaking the streak — now the next day surfaces a banner letting the user confirm they skipped it, log it manually, or re-check Strava for that specific date.",
            ],
        },
    },
    {
        name: "Americano",
        tagline: "Generate and score Americano matches for padel/tennis with 3+ players.",
        status: "Planned",
        tags: ["React", "TypeScript"],
        // githubUrl: "https://github.com/<you>/<repo>",
        // liveUrl: "https://<your-live-site>",
    },
    {
        name: "Daily AI Digest",
        tagline: "Email summaries of credible AI news from the last 24 hours.",
        status: "Planned",
        tags: ["Automation", "Email", "AI"],
        // githubUrl: "https://github.com/<you>/<repo>",
        // liveUrl: "https://<your-live-site>",
    },
    {
        name: "Trivia Arena",
        tagline:
            "A Jeopardy-style multiplayer trivia game with a live host-controlled board, team steals, and a countdown timer, powered by a Spring Boot WebSocket backend and a React frontend.",
        status: "In progress",
        tags: ["React", "TypeScript", "Spring Boot", "Java"],
        githubUrl: "https://github.com/Cecinordahl/trivia-arena",
        liveUrl: "https://trivia-arena.onrender.com/",
    },
    {
        name: "Casa 360",
        tagline: "Landing page for house rental",
        status: "Planned",
        tags: ["InsertTag1Here", "InsertTag2Here", "InsertTag2Here"],
        // githubUrl: "https://github.com/<you>/<repo>",
        // liveUrl: "https://<your-live-site>",
    },
    {
        name: "TanPlan",
        tagline: "A mobile-first sunscreen planner that schedules reapplication reminders throughout the day based on live UV forecasts, swims, and skin sensitivity.",
        status: "Beta",
        tags: ["React", "TypeScript", "Firebase", "Tailwind CSS"],
        githubUrl: "https://github.com/Cecinordahl/tan-plan",
        liveUrl: "https://tan-plan.vercel.app/",
    },
    {
        name: "Braut & Rosé",
        tagline: "Four couples on the same summer trip, arriving on different dates from different cities and staying in a mix of shared and separate places — all the coordinating was happening in a group chat, where details got buried and re-asked constantly. I built a shared trip planner so everyone could see the same itinerary notes, bookings, and schedules in real time and add to them directly, instead of scrolling back through chat history.",
        status: "Live",
        tags: ["React", "Vite", "Firebase", "Tailwind CSS"],
        githubUrl: "https://github.com/Cecinordahl/braut-og-rose",
        liveUrl: "https://braut-og-rose.vercel.app/",
        images: [
            "/images/projects/braut-og-rose/1.png",
            "/images/projects/braut-og-rose/2.png",
            "/images/projects/braut-og-rose/3.png",
            "/images/projects/braut-og-rose/4.png",
        ],
        details: {
            summary: "No accounts — everyone in the group unlocks the same shared trip with one passcode, and every device sees itinerary notes, bookings, and match/flight state update live via Firestore.",
            highlights: [
                "Live flight status via the AeroDataBox API, proxied through a Vercel serverless function so the RapidAPI key never reaches the client; results are cached in localStorage for 15 minutes to stay within the free tier's quota, with a manual refresh and a graceful fallback if the provider is unavailable.",
                "Live World Cup schedule and scores via ESPN's public scoreboard endpoint (no API key needed, since API-Football's free tier excludes the 2026 tournament) — matches are looked up by expected UTC kickoff time rather than team name, since most fixtures start as 'winner of X' placeholders that resolve automatically as ESPN's data updates through the earlier rounds.",
                "Real-time shared editing via Firebase Firestore's onSnapshot listeners — day notes, bookings, and match state sync live across every device in the group with no login, just a shared passcode on first visit.",
                "Packing lists export as plain text via the Web Share API (falling back to clipboard copy), formatted to paste cleanly into Notes and become a checklist there.",
                "Third-party fetches for flights and matches are staggered client-side to stay under provider rate limits, with a server-side retry-once-on-429 for extra resilience.",
            ],
            challenges: [
                "Penalty-shootout wins showed as a flat 0-0: ESPN marks these games with a separate STATUS_FINAL_PEN status and reports each team's shootoutScore apart from the 90-minute score, which the UI was initially dropping — fixed by reading and displaying the shootout score explicitly.",
                "All three tracked flights fetched simultaneously when the info card opened, tripping AeroDataBox's per-second rate limit — fixed by staggering client-side fetches 1.5s apart per flight and adding a server-side retry-once-on-429 with a clearer 'too many requests' message instead of a generic error.",
                "A data-loss race condition: booking add/update/delete could fire before the initial Firestore snapshot had loaded, rebuilding the bookings array from empty defaults and silently wiping everyone else's bookings — fixed by making those actions no-op until real data has loaded, with a loading state shown instead of exposing the controls early.",
            ],
        },
    },
    {
        name: "Pocket Phrases",
        tagline: "A situation-based travel phrase learner that builds short Spanish/French/German lessons for a chosen or described situation, with a Norwegian Bokmål UI.",
        status: "Live",
        tags: ["React", "TypeScript", "Java", "Spring Boot", "Anthropic API", "Firebase"],
        githubUrl: "https://github.com/Cecinordahl/pocket-phrases",
        liveUrl: "https://pocket-phrases.vercel.app",
    },
];

export const hobbyProjects: Project[] = parseContent(ProjectSchema, rawHobbyProjects, "content/projects.ts");
