import {parseContent, type Project, ProjectSchema} from "./schema.ts";

export type {Project};

const rawHobbyProjects = [
    {
        name: "EuroBonus Buddy",
        tagline: "I track my SAS EuroBonus status-point collecting in a personal Excel file with a dozen tabs — handy for me, but I don't want to hand over the whole document when friends and I compare notes on the cheapest way to the next tier, and it's honestly a mess to look at. EuroBonus Buddy is meant to replace it: a personal tracker for point and status data, plus a planner that compares different paths to a status goal — buying points outright, stacking car rentals, or a mix of both — ranked by cost or by speed, with a clean overview worth actually sharing. The plan is for anyone to be able to create their own account and track their own progress the same way, not just me.",
        status: "Planned",
        tags: ["React", "TypeScript", "Vite"],
        githubUrl: "https://github.com/Cecinordahl/eurobonusbuddy",
        // liveUrl: "https://<your-live-site>",
        details: {
            summary: "Enter your current status points, target tier, and months remaining in your qualification period; the planner generates a handful of candidate plans to close the gap and ranks them by either total cost or how fast they'd complete.",
            highlights: [
                "The \"buy Level Points\" option encodes SAS's actual eligibility rules rather than just offering a slider: it checks you're at least 6 months into the qualification period and have already earned the tier-specific minimum before allowing a purchase, then caps the amount at the tier's official ceiling and rounds to SAS's 100-point purchase blocks.",
                "Plans with an unknown cost (like car rentals, whose real price isn't modeled yet) are still shown and ranked, but explicitly flagged with a warning rather than silently guessed at or hidden, so an uncosted plan is never mistaken for a free one.",
                "The planner generates several candidate plans for the same goal — buying points outright, stacking multiple car rentals, or a hybrid of both — and ranks them by whichever optimization mode is selected: cheapest total cost, or fastest to close the gap.",
            ],
        },
    },
    {
        name: "WorkoutChallenge",
        tagline: "Inspired by Oslo Maraton's Julechallenge — pick a total distance and hit it by Christmas Eve — but frustrated it only ran in December with a flat, unskippable daily distance, I wanted that same not-knowing-what-today-brings motivation available year-round. WorkoutChallenge lets you set any date range and a total km goal, then generates a varied day-by-day plan with harder 'hero' days and lighter recovery days instead of splitting the distance evenly, tracking completion, streaks, and points with automatic Strava sync.",
        status: "Live",
        tags: ["React", "TypeScript", "Firebase", "Tailwind CSS", "Strava API", "Vercel"],
        githubUrl: "https://github.com/Cecinordahl/workout-challenge",
        liveUrl: "https://workout-challenge-app.vercel.app/",
        images: [
            "/images/projects/workout-challenge/1.png",
            "/images/projects/workout-challenge/2.png",
            "/images/projects/workout-challenge/3.png",
            "/images/projects/workout-challenge/4.png",
            "/images/projects/workout-challenge/5.png",
            "/images/projects/workout-challenge/6.png",
        ],
        details: {
            summary: "You set a total distance or time goal, a daily minimum and maximum, and a date range; the app generates a randomized day-by-day plan within those bounds and tracks your progress against it, syncing automatically from Strava.",
            highlights: [
                "The daily plan is generated by a seeded-random engine that distributes the total goal unevenly across the challenge window — ramping difficulty gradually week over week, easing the final week, and mixing in randomized \"hero\" days (1.4-1.6x the baseline) and lighter recovery days (0.5-0.6x) — instead of splitting the goal into equal daily chunks.",
                "Strava activities sync automatically: a webhook subscription notifies a Vercel serverless function the moment a qualifying run posts, which matches it to that day's active challenge and logs it without the user opening the app.",
                "Hero days are worth double the points of normal or recovery days, and the streak counter tolerates days a user explicitly marks as skipped while still breaking on days left unmarked, rewarding honest tracking over silently missed days.",
                "Points and streak calculations are deliberately duplicated between the client and the Vercel functions (each copy comments pointing at its counterpart) so the UI and the webhook-driven auto-logging path stay consistent without sharing a runtime.",
            ],
            challenges: [
                "Firebase Admin's auth module pulled in a JWT library that's ESM-only, which crashed every serverless function in production with ERR_REQUIRE_ESM the moment the new Strava routes started calling it — fixed by pinning that dependency to its last dual CJS/ESM major version via an npm override.",
                "The daily min/max distance inputs used native number-input steppers, which increment from whatever value is already there without rounding — so starting from a suggested 1.2km and clicking up repeatedly produced 2.2, 3.2, and so on instead of whole numbers; replaced with a custom stepper that rounds to the nearest step and clamps both bounds to the challenge's total goal.",
                "A day with no logged result used to be permanently marked missed with no way back, silently breaking the streak — now the next day surfaces a banner letting the user confirm they skipped it, log it manually, or re-check Strava for that specific date.",
            ],
        },
    },
    {
        name: "Americano",
        tagline: "Some friends and I started playing Americano at padel, and the app we used worked fine with 4+ players and plenty of time — but with only 3 players, or with just 10 minutes left on a court booking after a longer game, none of the apps I tried had a mode that fit. Americano is my own version built to cover those gaps: it supports 3-player games and lets you pick the shortest possible format for whatever group size and time you actually have.",
        status: "Planned",
        tags: ["Swift", "SwiftUI", "SwiftData"],
        // githubUrl: "https://github.com/<you>/<repo>",
        // liveUrl: "https://<your-live-site>",
        manualDates: { createdAt: "2025-12-21", pushedAt: "2026-01-04" },
        details: {
            summary: "This iOS app generates and manages Americano-style tournaments for racket sports, with support for both traditional doubles Americano (4+ players) and a custom 3-player singles variant. Users create a tournament, get an auto-generated match schedule, record scores round by round, and track a live leaderboard, with everything saved locally so a tournament can be resumed later.",
            highlights: [
                "Built as a native iOS app in SwiftUI with SwiftData persistence, so tournaments, players, matches, and scores are saved automatically between launches.",
                "The 3-player mode uses a custom singles rotation — each round has one player sit out while the other two play, and the resting slot rotates evenly so everyone alternates fairly between playing and resting.",
                "Doubles scheduling rotates player order between rounds and groups players into courts of four (court count is configurable so multiple matches can run per round), auto-forming teams and assigning byes when the player count doesn't divide evenly.",
                "Doubles score targets are restricted to multiples of four (8, 12, 16, 20...) so every player serves the same number of times, matching how Americano is conventionally played — a rule most Americano apps don't enforce.",
                "Score entry isn't blocked, but a mismatched total against the configured points target shows a warning, and a match must be explicitly locked before it counts toward the leaderboard, so an in-progress or miskeyed score can't silently skew the standings.",
            ],
            challenges: [
                "Standard Americano scheduling assumes four players, so 3-player games needed a custom rotation: one player sits out each round while the other two play, with the resting slot rotating evenly across players.",
                "A score target like 11 points gave players an unequal number of serves in doubles — fixed by restricting doubles targets to multiples of four so serves always come out even.",
                "Switching between saved tournaments was leaking standings from one tournament into another because the leaderboard wasn't scoped to the active tournament's matches — fixed by recalculating each player's total directly from the current tournament's stored matches.",
                "Adding new persisted properties to the SwiftData models broke the local model container at launch — resolved by rebuilding the local development data store so its schema matched the updated models.",
            ],
        },
    },
    {
        name: "Daily AI Digest",
        tagline: "Email summaries of credible AI news from the last 24 hours.",
        status: "Planned",
        tags: ["Automation", "Email", "AI"],
        // githubUrl: "https://github.com/<you>/<repo>",
        // liveUrl: "https://<your-live-site>",
    },
    {
        name: "Trivia Arena",
        tagline:
            "I was usually the one building the Kahoot quiz for game night, and Kahoot has no way to generate a quiz automatically by category — I had to write every question and answer myself, which meant I already knew them all and couldn't actually play. Trivia Arena is my own answer to that: a real-time, Jeopardy-style board across 12 categories where teams buzz in, wrong or missed answers open a steal for the other team, and everything syncs live over WebSocket. Today's board runs on a curated 60-question bank; automatic per-category question generation — the actual fix for not being able to play my own game — is next.",
        status: "In progress",
        tags: ["React", "TypeScript", "Spring Boot", "Java"],
        githubUrl: "https://github.com/Cecinordahl/trivia-arena",
        liveUrl: "https://trivia-arena.onrender.com/",
        details: {
            summary: "A host creates a room, organizes players into teams, and starts the game from a lobby; the board shows 12 categories × 5 point values, and whoever's turn it is picks a question for everyone to answer against a host-configurable countdown.",
            highlights: [
                "Each question round is a server-authoritative two-phase timer: the picking team's exclusive window to answer, followed — on a wrong or missed answer — by a steal window opened to every other team, each phase running its own scheduled timeout and broadcasting the change over WebSocket.",
                "Game state (rooms, teams, board, scores) is pushed to every connected client in real time over WebSocket/STOMP, so the shared board, buzz-ins, and score changes stay in sync across host and player screens without polling.",
                "The frontend and backend ship as a single Docker image — Spring Boot serves the built React app as static resources from its own JAR — so the whole game runs from one process on Render's free tier.",
                "The host sets an answer countdown between 10 and 300 seconds when starting the game, broadcast live to every client so everyone sees the same clock.",
            ],
            challenges: [
                "Expanding from a handful of categories to twelve for full coverage broke the fixed-width board — columns started overlapping their own text — fixed by making the board grid scroll horizontally with a sane per-column minimum width instead of squeezing everything to fit.",
            ],
        },
    },
    {
        name: "Casa 360",
        tagline: "My family rents out our vacation home in Spain through Airbnb and a rental agency, and my mom kept fielding the same questions over and over — Airbnb's messaging isn't built for organizing a house manual, transportation tips, restaurant and golf/activity booking info, and we wanted guests to have genuinely good information, not just the bare minimum. Casa 360 is a bilingual (English/Norwegian) guest guide built for the phone: practical info like restaurants and activities is publicly browsable, house-specific details like WiFi and appliances sit behind a simple guest code, and an admin panel lets my parents add and edit all of it themselves without touching code. Eventually we'd like to use it to move bookings off Airbnb and the agency entirely and cut out the cut they both take.",
        status: "Live",
        tags: ["React", "TypeScript", "Firebase", "Cloudinary", "Vercel", "i18next"],
        githubUrl: "https://github.com/Cecinordahl/casa360",
        liveUrl: "https://casa-360.vercel.app/",
        details: {
            summary: "Three surfaces in one app: a public guide (restaurants, groceries, activities, practical info) anyone can browse, a guest-code-gated house manual (WiFi, appliances, house rules, emergency info), and a Firebase-authenticated admin panel for managing all of it, including image uploads and guest-code rotation.",
            highlights: [
                "There's no traditional backend — the app talks to Firestore directly from the browser, and firestore.rules is the actual access-control layer, with an /admins allowlist collection gating writes rather than relying on being signed in alone.",
                "The guest code that gates the house manual is enforced through the Firestore document path itself (houseManual/{code}/sections/...) rather than a field check, since security rules can't inspect a value the client typed into a form on a plain read — rotating the code means batch-copying the section documents to the new path before flipping the pointer.",
                "Images are hosted on Cloudinary instead of Firebase Storage — a deliberate choice to keep the whole Firebase project on the free Spark plan with no billing account attached, since Storage requires the paid Blaze plan; uploads go through two small Vercel serverless functions that verify the caller against the admin allowlist before handing out a short-lived signed upload URL, so the Cloudinary API secret never reaches the browser.",
                "Uploaded photos have their EXIF data (including GPS coordinates) stripped in the browser by re-encoding the image on a canvas before it ever leaves the client, so guest or house photos never leak location metadata.",
                "The admin panel is a full CRUD interface with drag-and-drop image reordering, so non-technical family members can add and edit restaurants, activities, and manual content without touching code.",
            ],
            challenges: [
                "firebase-admin's ID-token verification pulled in a JWT library that, from v14 onward, requires jose@6 (ESM-only) — calling verifyIdToken() from a Vercel serverless function crashed with ERR_REQUIRE_ESM; fixed by pinning firebase-admin to the 13.x line, which uses jose@4 (still CJS).",
            ],
        },
    },
    {
        name: "TanPlan",
        tagline: "On a trip to France with friends, we kept setting manual phone timers to remind ourselves to reapply sunscreen — and still forgot, because nobody wants a sunburn ruining a beach day. TanPlan replaces the guesswork: you build a personal skin profile using the standardized Fitzpatrick test, then generate a reapplication plan for the day that accounts for your location's UV forecast, the sun-exposure window, and roughly how many swim or lunch breaks you're taking. A one-tap reset re-plans the rest of the day from that moment whenever you've just been in the water.",
        status: "Beta",
        tags: ["React", "TypeScript", "Firebase", "Tailwind CSS"],
        githubUrl: "https://github.com/Cecinordahl/tan-plan",
        liveUrl: "https://tan-plan.vercel.app/",
        details: {
            summary: "You answer 5 quick Fitzpatrick questions to get a skin type, then for each day enter a location, a sun-exposure window, and roughly how many swim and lunch breaks you expect; the app pulls an hourly UV forecast for that location and generates a reapplication schedule around it, exportable as a calendar file.",
            highlights: [
                "The reapplication interval tightens from a 2-hour baseline to 90 minutes automatically whenever the UV forecast at that time of day hits 8 or higher, or unconditionally for young children, easily-burning skin, or the two lightest Fitzpatrick types — so the schedule adapts to both the day's actual UV and the person's sensitivity, not just a flat rule.",
                "Swim and lunch breaks aren't just markers on the schedule — swim breaks are spread evenly across the sun-exposure window as their own reapplication events, and lunch adds a reapplication both before and after the break, then anything within 30 minutes of another event gets merged so the plan never asks for two applications back to back.",
                "The \"I just swam\" reset button doesn't regenerate the whole day: it keeps everything already logged up to that moment untouched, then re-runs the same scheduling logic for only the time remaining, using the current moment as a fresh starting point instead of guessing when the next swim will happen.",
                "The Fitzpatrick skin-type quiz results, UV forecast, and location geocoding all run through Open-Meteo's free API with no key required, keeping the app's data costs at zero outside of Firebase's own free tier.",
                "Plan generation is pure, I/O-free TypeScript — no Firebase, no fetch calls — fully covered by unit tests, and kept deliberately separate from the Firebase/Open-Meteo service layer that feeds it real data.",
            ],
            challenges: [
                "The Fitzpatrick skin-type questionnaire originally had overlapping and ambiguous answer options (eye-color choices that meant the same thing, unclear tan-shade and freckle wording), leading to inconsistent self-reported skin types — fixed by deduplicating options, clarifying the wording, and adding a per-question info toggle with examples.",
            ],
        },
    },
    {
        name: "Braut & Rosé",
        tagline: "Four couples on the same summer trip, arriving on different dates from different cities and staying in a mix of shared and separate places — all the coordinating was happening in a group chat, where details got buried and re-asked constantly. I built a shared trip planner so everyone could see the same itinerary notes, bookings, and schedules in real time and add to them directly, instead of scrolling back through chat history.",
        status: "Live",
        tags: ["React", "Vite", "Firebase", "Tailwind CSS"],
        githubUrl: "https://github.com/Cecinordahl/braut-og-rose",
        liveUrl: "https://braut-og-rose.vercel.app/",
        images: [
            "/images/projects/braut-og-rose/1.png",
            "/images/projects/braut-og-rose/2.png",
            "/images/projects/braut-og-rose/3.png",
            "/images/projects/braut-og-rose/4.png",
        ],
        details: {
            summary: "No accounts — everyone in the group unlocks the same shared trip with one passcode, and every device sees itinerary notes, bookings, and match/flight state update live via Firestore.",
            highlights: [
                "Live flight status via the AeroDataBox API, proxied through a Vercel serverless function so the RapidAPI key never reaches the client; results are cached in localStorage for 15 minutes to stay within the free tier's quota, with a manual refresh and a graceful fallback if the provider is unavailable.",
                "Live World Cup schedule and scores via ESPN's public scoreboard endpoint (no API key needed, since API-Football's free tier excludes the 2026 tournament) — matches are looked up by expected UTC kickoff time rather than team name, since most fixtures start as 'winner of X' placeholders that resolve automatically as ESPN's data updates through the earlier rounds.",
                "Real-time shared editing via Firebase Firestore's onSnapshot listeners — day notes, bookings, and match state sync live across every device in the group with no login, just a shared passcode on first visit.",
                "Packing lists export as plain text via the Web Share API (falling back to clipboard copy), formatted to paste cleanly into Notes and become a checklist there.",
                "Third-party fetches for flights and matches are staggered client-side to stay under provider rate limits, with a server-side retry-once-on-429 for extra resilience.",
            ],
            challenges: [
                "Penalty-shootout wins showed as a flat 0-0: ESPN marks these games with a separate STATUS_FINAL_PEN status and reports each team's shootoutScore apart from the 90-minute score, which the UI was initially dropping — fixed by reading and displaying the shootout score explicitly.",
                "All three tracked flights fetched simultaneously when the info card opened, tripping AeroDataBox's per-second rate limit — fixed by staggering client-side fetches 1.5s apart per flight and adding a server-side retry-once-on-429 with a clearer 'too many requests' message instead of a generic error.",
                "A data-loss race condition: booking add/update/delete could fire before the initial Firestore snapshot had loaded, rebuilding the bookings array from empty defaults and silently wiping everyone else's bookings — fixed by making those actions no-op until real data has loaded, with a loading state shown instead of exposing the controls early.",
            ],
        },
    },
    {
        name: "Pocket Phrases",
        tagline: "I've used Duolingo for years, but it's never had an \"I'm going to Paris next week and need touristy vocab\" mode — and the grammar exercises are often more complexity than I actually want when I just need practice before a trip. Pocket Phrases is my stripped-down alternative: situation-based lessons (restaurant, transport, emergencies, and more) for Spanish, French, and German, built around flashcard drills and simple quizzes rather than grammar drilling. I also used it to try building on top of Claude — when none of the premade categories fit, a free-text box lets you describe your situation and generates a lesson from that instead.",
        status: "Live",
        tags: ["React", "TypeScript", "Java", "Spring Boot", "Anthropic API", "Firebase"],
        githubUrl: "https://github.com/Cecinordahl/pocket-phrases",
        liveUrl: "https://pocket-phrases.vercel.app",
        details: {
            summary: "Pick a language and either a premade situation (restaurant, transport, emergencies, and other prebuilt modes) or describe your own; the app returns a short lesson you work through three ways — read, flashcard drill, and quiz — with no accounts, just progress saved locally on your device.",
            highlights: [
                "Every lesson — whether sampled from the prebuilt phrase pool, generated by Claude from free text, or shuffled at random — is normalized to the exact same Lesson/Phrase shape on the backend, so the read/drill/quiz screens only ever render one format regardless of where the content came from.",
                "The free-text generator uses Anthropic's structured outputs (a schema derived from a GeneratedLesson record) rather than prompting for JSON and parsing the response text, so the model's output is validated against a schema at the API level instead of hoping the text comes back parseable.",
                "If the Claude call errors, gets refused, or the SDK throws for any reason, the backend catches it and serves a prebuilt \"Turist-essensielt\" lesson instead of an error screen, so a flaky AI call never blocks the app mid-use.",
                "Prebuilt content is a local JSON seed file sampled and shuffled per request rather than a Firestore collection — a deliberate call, since a Firestore round-trip (and the service-account setup it requires just to run locally) added latency and friction for content that barely changes; the sampling service sits behind a small interface so swapping in a Firestore-backed version later is a one-file change.",
                "An optional Firestore-backed email whitelist can gate the whole app behind a single flag — fully implemented, off by default, and explicitly documented as a soft privacy gate rather than real authentication, since anyone who knows a whitelisted email could still type it in.",
            ],
            challenges: [
                "Render's free tier puts the backend to sleep after inactivity, so the first request after a while took 10-30 seconds and looked like the app had frozen — fixed by detecting the slow initial load and showing an explanatory cold-start message instead of a blank screen.",
                "Free-text lesson generation takes a few seconds for the Claude call to return, which read as an unresponsive button until a loading state was added to make the wait legible.",
            ],
        },
    },
    {
        name: "Voyage Collective",
        tagline: "It started with a trip to Copenhagen, where I shot photos for a friend's brand collaboration with the Marriott — and we had so much fun working together that we wanted to keep doing it, at a bigger scale, without folding into a larger agency or bringing in outside people. That meant we needed a real front door: a way for hotels and brands to see us as a small, boutique two-person agency rather than two individual creators reaching out separately. This site gives us that — real audience stats, sample work, and clear collaboration packages a brand can browse and contact directly.",
        status: "Live",
        tags: ["React", "TypeScript", "Vite", "Tailwind CSS", "Vercel Serverless Functions", "Resend"],
        githubUrl: "https://github.com/Cecinordahl/voyage-collective",
        liveUrl: "https://voyage-collective.vercel.app",
        details: {
            highlights: [
                "Self-hosted the Bodoni Moda display serif as local woff2 files instead of loading it from Google Fonts at runtime, keeping the page free of third-party network requests in line with its no-tracking privacy stance.",
                "Contact form validation rules live in one shared TypeScript module imported by both the React form and the Vercel serverless function, so client-side and server-side validation can never drift out of sync.",
                "A hidden honeypot field silently returns a fake success response to bots that fill it in, blocking spam submissions without a CAPTCHA or third-party script.",
                "No database anywhere — the /api/contact function validates a submission, emails it via Resend, and discards it, matching a GDPR data-minimization approach spelled out in a companion privacy-notice page.",
                "Creators, collaboration packages, and portfolio photos are all modeled as typed data objects in src/content/, so the two non-technical owners can edit copy, swap photos, or add real client case studies without touching any component code.",
                "The portfolio's client-work subsection is coded to hide itself automatically whenever its data array is empty, letting the site ship honestly before any real case studies exist instead of showing placeholder clients.",
            ],
            challenges: [
                "The contact API worked in local dev but crashed in production with a 500 error — Vercel's stricter ESM module resolution required an explicit .js extension on a relative import that the local TypeScript config didn't flag; fixed by adding the extension.",
                "Resend's sandbox mode, active before a sending domain is verified, turned out to only deliver email to the account's own registered address regardless of the configured recipient; discovered while testing the live form, and worked around by pointing the recipient env var at that address until domain verification is complete.",
            ],
        },
    },
    {
        name: "Sportfeed",
        tagline: "I follow teams and athletes across a handful of different sports, and kept having to Google each one separately just to check if they were playing — with so many to track, matches and races were easy to miss entirely. Sportfeed collects them all into one dashboard: search and favorite any team, athlete, or racing series across football, F1, golf, and tennis, and see every upcoming or live event for your favorites merged into a single chronologically sorted list, with anything live pinned to the top.",
        status: "In progress",
        tags: ["React", "TypeScript", "Java", "Spring Boot", "Firebase"],
        githubUrl: "https://github.com/Cecinordahl/sportfeed",
        // liveUrl omitted: the backend API is deployed on Render, but the frontend dashboard isn't deployed yet (README lists it as "Coming soon").
        details: {
            summary: "You search across sports for teams, athletes, or racing series and add favorites; the dashboard endpoint then merges upcoming and live events for everything you follow into one chronological feed, live events pinned to the top.",
            highlights: [
                "Every sport is served through a single SportsDataProvider interface resolved per sport via a ProviderRegistry, so adding a new data source — like swapping ESPN's F1 feed for a different provider — means adding one class and changing one registry entry rather than touching the rest of the codebase.",
                "Favorites are stored in Firestore with an externalId namespaced by provider (e.g. espn:soccer:eng.1:359), so swapping the data provider behind one sport never invalidates or collides with favorites saved for another.",
                "The dashboard endpoint merges upcoming events across every sport a user follows into one chronologically sorted list, with any currently-live event pinned to the top regardless of sport.",
                "Adding a favorite is idempotent by externalId, so re-favoriting a team or athlete that's already saved doesn't create a duplicate.",
                "The backend deploys to Render's free tier as a multi-stage Docker build (JDK 21 to compile, JRE-only for the final image) since Render's free tier has no native Java runtime; a scheduled GitHub Actions workflow pings /health every 10 minutes to counteract the free tier's cold-start sleep.",
            ],
        },
    },
    {
        name: "Phase Train",
        tagline: "I train with Garmin and Runna but kept running into two things they handle badly: neither lets me build a plan around two goals at once — a faster 3K and a faster 10K, together — and if I get sick and pause, the plan just resumes exactly where it left off, with no adjustment for the time off or the fitness dip that follows. Phase Train is my attempt at something that reasons about my actual day-to-day situation — including where I am in my menstrual cycle — instead of handing me a fixed plan. So far that means real session logging, weekly plans, and a genuine pause/resume mechanism: marking yourself sick pauses every future session without touching what's already logged, and marking recovered resumes only from today forward. Dual-goal planning, cycle-phase-aware adjustments, and adapting the plan itself after a break are the next pieces to build.",
        status: "In progress",
        tags: ["Java", "Spring Boot", "PostgreSQL", "React", "TypeScript"],
        githubUrl: "https://github.com/Cecinordahl/phase-train",
        details: {
            highlights: [
                "Real server-side session-cookie authentication via Spring Security with CSRF protection, and self-service signup gated behind an email allowlist (defaults to just my own address) so a single-user MVP can't be signed up to by anyone else.",
                "A sick/healthy cascade: marking yourself sick pauses every still-planned session from that date forward, and marking recovered resumes only sessions from today forward — sessions that already fell inside the illness window stay marked as history rather than being retroactively resurrected.",
                "The domain model keeps what was planned (WeeklyPlan/PlannedSession) separate from what actually happened (RunSession/StrengthSession/ExerciseLog), with a RunSessionSource field distinguishing a manually logged run from one meant to sync from Strava later.",
                "LoadRule already exists as its own entity and DTO so a training-load rule engine can be layered on top of existing data later, even though the enforcement logic itself isn't built yet.",
                "Local dev runs on Docker Compose Postgres with Flyway auto-migrating the schema on backend startup.",
            ],
        },
    },
    {
        name: "Eggspecting",
        tagline: "I want one place that tells me where I am in my cycle and what that means for trying to conceive — when to start ovulation testing, how often and what time of day, and that the egg typically drops within about 48 hours of a peak result — instead of piecing it together from scattered corners of the internet. Eggspecting is meant to be that single source: cycle-based guidance alongside food advice, workout guidance by cycle phase, and a sense of what's actually normal (chemical pregnancies, a late period) so those moments don't cause unnecessary panic. It's planned first for myself and friends who want it, with the idea of opening it up to more women later.",
        status: "Planned",
        tags: ["Health", "Cycle Tracking", "Fertility"],
        // githubUrl: "https://github.com/<you>/<repo>",
        // liveUrl: "https://<your-live-site>",
    },
];

export const hobbyProjects: Project[] = parseContent(ProjectSchema, rawHobbyProjects, "content/projects.ts");
